server:
  port: 10003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10002/eureka/

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
        
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  #file: zuul.log
  file: /var/kido/logs/zuul.log
              
zuul:
  routes:
    userservice:
      path: /userservice/**
      serviceId: User-service
      stripPrefix: true
    productservice:
      path: /productservice/**
      serviceId: Product-service
      stripPrefix: true
    orderservice:
      path: /orderservice/**
      serviceId: Order-service
      stripPrefix: true
    newsservice:
      path: /newsservice/**
      serviceId: News-service
      stripPrefix: true
    eventservice:
      path: /eventservice/**
      serviceId: Event-service
      stripPrefix: true
    shipperservice:
      path: /shipperservice/**
      serviceId: Shipper-service
      stripPrefix: true
    searchservice:
      path: /searchservice/**
      serviceId: Search-service
      stripPrefix: true
    salemanservice:
      path: /salemanservice/**
      serviceId: Saleman-service
      stripPrefix: true
  retryable: true
  #ribbonIsolationStrategy:THREAD
  ribbon:
    eager-load:
      enabled: true
  #semaphore:
  #  max-semaphores: 5000
  #eureka:
  #  User-service:
  #    semaphore:
  #      maxSemaphores: 5000
  #eureka:
  #  Product-service:
  #    semaphore:
  #      maxSemaphores: 5000
  #eureka:
  #  Order-service:
  #    semaphore:
  #      maxSemaphores: 5000
  #eureka:
  #  News-service:
  #    semaphore:
  #      maxSemaphores: 5000
 

hystrix:
  command:
    User-service:
      execution:
        isolation:
          strategy: THEARD
          thread:
            timeoutInMilliseconds: 120000
    Product-service:
      execution:
        isolation:       
          strategy: THEARD
          thread:
            timeoutInMilliseconds: 120000
    Order-service:
      execution:
        isolation:
          thread:
          strategy: THEARD
          thread:
            timeoutInMilliseconds: 120000
    News-service:
      execution:
        isolation:
          thread:
          strategy: THEARD
          thread:
            timeoutInMilliseconds: 120000
    Event-service:
      execution:
        isolation:
          thread:
          strategy: THEARD
          thread:
            timeoutInMilliseconds: 120000
    Shipper-service:
      execution:
        isolation:
          thread:
          strategy: THEARD
          thread:
            timeoutInMilliseconds: 120000
    Search-service:
      execution:
        isolation:
          thread:
          strategy: THEARD
          thread:
            timeoutInMilliseconds: 120000
    Saleman-service:
      execution:
        isolation:
          thread:
          strategy: THEARD
          thread:
            timeoutInMilliseconds: 120000

User-service:
  ribbon:
    #NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    #listOfServers: http://localhost:33001,http://localhost:33002,http://61.28.226.134:33003
    #ConnectTimeout: 10000
    #ReadTimeout: 10000
    MaxTotalHttpConnections: 2000
    MaxConnectionsPerHost: 1000
    maxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true
    ReadTimeout: 120000
    ConnectTimeout: 10000
    retryableStatusCodes: 404,502
    eureka:
      enabled: true
    
Product-service:
  ribbon:
    #NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    #listOfServers: http://localhost:33011,http://localhost:33012
#    ConnectTimeout: 10000
#    ReadTimeout: 10000
    MaxTotalHttpConnections: 2000
    MaxConnectionsPerHost: 1000
    maxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true
    ReadTimeout: 120000
    ConnectTimeout: 10000
    retryableStatusCodes: 404,502
    eureka:
      enabled: true
      
Order-service:
  ribbon:
    #NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    #listOfServers: http://localhost:33021,http://localhost:33022
#    ConnectTimeout: 10000 
#    ReadTimeout: 10000
    MaxTotalHttpConnections: 2000
    MaxConnectionsPerHost: 1000
    maxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true
    ReadTimeout: 120000
    ConnectTimeout: 10000
    retryableStatusCodes: 404,502
    eureka:
      enabled: true
      
News-service:
  ribbon:
    #NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    #listOfServers: http://localhost:33031,http://localhost:33032
#    ConnectTimeout: 10000
#    ReadTimeout: 10000
    MaxTotalHttpConnections: 2000
    MaxConnectionsPerHost: 1000
    maxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true
    ReadTimeout: 120000
    ConnectTimeout: 10000
    retryableStatusCodes: 404,502
    eureka:
      enabled: true
      
Event-service:
  ribbon:
    #NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    #listOfServers: http://localhost:33031,http://localhost:33032
#    ConnectTimeout: 10000
#    ReadTimeout: 10000
    MaxTotalHttpConnections: 2000
    MaxConnectionsPerHost: 1000
    maxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true
    ReadTimeout: 120000
    ConnectTimeout: 10000
    retryableStatusCodes: 404,502
    eureka:
      enabled: true

Shipper-service:
  ribbon:
    #NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    #listOfServers: http://localhost:33031,http://localhost:33032
#    ConnectTimeout: 10000
#    ReadTimeout: 10000
    MaxTotalHttpConnections: 2000
    MaxConnectionsPerHost: 1000
    maxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true
    ReadTimeout: 120000
    ConnectTimeout: 10000
    retryableStatusCodes: 404,502
    eureka:
      enabled: true

Search-service:
  ribbon:
    #NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    #listOfServers: http://localhost:33031,http://localhost:33032
#    ConnectTimeout: 10000
#    ReadTimeout: 10000
    MaxTotalHttpConnections: 2000
    MaxConnectionsPerHost: 1000
    maxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true
    ReadTimeout: 120000
    ConnectTimeout: 10000
    retryableStatusCodes: 404,502
    eureka:
      enabled: true
Saleman-service:
  ribbon:
    #NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    #listOfServers: http://localhost:33031,http://localhost:33032
#    ConnectTimeout: 10000
#    ReadTimeout: 10000
    MaxTotalHttpConnections: 2000
    MaxConnectionsPerHost: 1000
    maxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true
    ReadTimeout: 120000
    ConnectTimeout: 10000
    retryableStatusCodes: 404,502
    eureka:
      enabled: true